name: Quick Build

on:
  pull_request:
    paths:
      - '.github/quick-build-trigger/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup JDK 17
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6.3.0

      - name: Prepare Assets
        run: |
          echo "" > "$GITHUB_WORKSPACE/app/src/main/assets/18PlusList.txt"

      - name: Prepare Release Signing
        run: |
          cp "$GITHUB_WORKSPACE/.github/workflows/legado.jks" "$GITHUB_WORKSPACE/app/legado.jks"
          sed '$a\RELEASE_STORE_FILE=./legado.jks' "$GITHUB_WORKSPACE/gradle.properties" -i
          sed '$a\RELEASE_KEY_ALIAS=legado' "$GITHUB_WORKSPACE/gradle.properties" -i
          sed '$a\RELEASE_STORE_PASSWORD=gedoor_legado' "$GITHUB_WORKSPACE/gradle.properties" -i
          sed '$a\RELEASE_KEY_PASSWORD=gedoor_legado' "$GITHUB_WORKSPACE/gradle.properties" -i

      - name: Quick ARM Release Build
        run: |
          chmod +x gradlew
          ./gradlew :app:assembleRelease -ParmOnly=true --build-cache --parallel --daemon --warning-mode all
